### PR TITLE
Fix: 2 file management bugs

### LINKED ISSUE #755: Problem with Deleting Files from S3
## Long story short
Deleting files from my S3 does not work.

## Expected behaviour
Files should be deleted.

## Actual behaviour
It's not deleting.

## Steps to reproduce
See pic above.

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

### LINKED ISSUE #760: Copy Files in the Datamanager Fails
## Long story short
"Drag&drop the “out_1” file into one of the datcore directories. Make sure it was correctly copied."
-> Seems not to work.

## Expected behaviour
Drag&drop the “out_1” file into one of the datcore directories. It was correctly copied.

## Actual behaviour
It's not copied. Please see Movie:

## Steps to reproduce
Please see above.

## Your environment
```json
[
  {
    "name": "osparc-simcore",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/"
  },
  {
    "name": "osparc-simcore UI ['clean']",
    "version": "57c704a",
    "url": "https://github.com/ITISFoundation/osparc-simcore/tree/57c704a/services/web/client/"
  },
  {
    "name": "qooxdoo-compiler",
    "version": "0.3.0-alpha.20190423-1234",
    "url": "https://github.com/qooxdoo/qooxdoo-compiler"
  },
  {
    "name": "qxapp",
    "version": "1.0.0",
    "url": ""
  },
  {
    "name": "qooxdoo framework",
    "version": "6.0.0-alpha-20190409-f79cc78",
    "url": "http://qooxdoo.org"
  },
  {
    "name": "qx-iconfont-fontawesome5",
    "version": "0.0.6",
    "url": "https://github.com/ITISFoundation/qx-iconfont-fontawesome5"
  },
  {
    "name": "qx-iconfont-material",
    "version": "0.1.4",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "qx-osparc-theme",
    "version": "0.4.6",
    "url": "https://github.com/ITISFoundation/qx-osparc-theme"
  },
  {
    "name": "socket.io",
    "version": "2.1.2",
    "url": "https://github.com/socketio/socket.io"
  },
  {
    "name": "jsondiffpatch",
    "version": "0.3.11",
    "url": "https://github.com/benjamine/jsondiffpatch"
  },
  {
    "name": "jsonTreeViewer",
    "version": "0.6.0",
    "url": "https://github.com/summerstyle/jsonTreeViewer"
  },
  {
    "name": "Ajv",
    "version": "6.5.0",
    "url": "https://github.com/epoberezkin/ajv"
  },
  {
    "name": "plotly",
    "version": "1.43.2",
    "url": "https://github.com/plotly/plotly.js"
  },
  {
    "name": "gridster",
    "version": "0.7.0",
    "url": "https://github.com/dsmorse/gridster.js"
  },
  {
    "name": "svg.js",
    "version": "2.6.4",
    "url": "https://github.com/svgdotjs/svg.js"
  }
]
```

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Fixes 2 bugs related to deleting and copying files.

## Related issue number
closes #760
closes #755

## Checklist

- [ ] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] **Runs in the swarm**
- [ ] If you design a new module, add your user to .github/CODEOWNERS

### CODE REVIEW

**Comment by odeimaiz** [comment]
Retry Deepcode

File: services/web/client/source/class/qxapp/data/Permissions.js [hunk 1]
```diff
@@ -97,7 +97,8 @@ qx.Class.define("qxapp.data.Permissions", {
     getLowerRoles(role) {
```
Comment (pcrespov) [inline services/web/client/source/class/qxapp/data/Permissions.js]: Shouldn't you just normalize the role names when loaded the first time instead of upper/lowering it at every call?

File: services/web/client/source/class/qxapp/data/Permissions.js [hunk 2]
```diff
@@ -97,7 +97,8 @@ qx.Class.define("qxapp.data.Permissions", {
...
       const lowerRoles = [];
       for (const r in this.self().ROLES) {
-        if (r === role) {
+        if (r.toLowerCase() === role.toLowerCase()) {
+          lowerRoles.push(r);
```
Comment (pcrespov) [inline services/web/client/source/class/qxapp/data/Permissions.js]: getLowerRoles(role) : This function returns you all roles until it matches the one you have? Aha ... by "lower" you mean "children" or "below" ...  
What if you have multiple inheritance? is the ROLES built in a special way?
Shouln't you use ``inherits`` instead?

File: services/web/client/source/class/qxapp/data/Permissions.js (hunk 1 above)
Comment (oetiker) [reply services/web/client/source/class/qxapp/data/Permissions.js]: why is the case of the roles even a problem? I would make sure it is consistent ... do not allow for wrong case
