### PR TITLE
Fix input node's title

### LINKED ISSUE #770: Fix Input's node label in nodeView
image

### PR DESCRIPTION
**Pull request by odeimaiz**
## What do these changes do?
Fixes the bug related to the node label in the NodePorts

## Related issue number
closes #770 
fixLabel

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] **Runs in the swarm**
- [ ] If you design a new module, add your user to .github/CODEOWNERS

### CODE REVIEW

File: services/web/client/source/class/qxapp/component/widget/NodePorts.js [hunk 1]
```diff
@@ -37,19 +37,18 @@ qx.Class.define("qxapp.component.widget.NodePorts", {
...
-    node.bind("label", label, "value");
+    this._setLayout(new qx.ui.layout.Grow());
 
     const nodeUIPorts = this.__nodeUIPorts = new qx.ui.container.Composite(new qx.ui.layout.VBox()).set({
       appearance: "node-ports"
     });
 
-    this.setIsInputModel(isInputModel);
-    this.setNode(node);
+    this.base(arguments, node.getLabel(), nodeUIPorts);
```
Comment (oetiker) [inline services/web/client/source/class/qxapp/component/widget/NodePorts.js]: calling the super class 'in the middle' indicates quite a lot of knowledge about the way the superclass constructoir is implemented :) is this necessary?

Comment (ignapas) [reply services/web/client/source/class/qxapp/component/widget/NodePorts.js]: I wouldn't say it is necessary, I did it to test the reusability of the PanelView, and it work first go so we left it like that. The superclass constructor is our code, so we really know how its implemented. There is probably room for a small refactor here, but this is out of the scope of this PR, I think.
